apiVersion: v1
kind: Service
metadata:
  name: prepsom-games-backend-service
spec:
  selector:
    app: prepsom-games-backend
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8000
  type: LoadBalancer
